// "use client";
// import { NavcontextProvider } from "@/context/Navcontext";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Alex_Brush, Montserrat } from "next/font/google";

const alexBrush = Alex_Brush({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-alexBrush",
});
const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Music App",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v-4"],
    shortcut: ["/apple.touch-icon.png"],
  },
};
export default function RootLayout({ children }) {
  return (
    // <NavcontextProvider>
    <html lang="en">
      <body
        className={`${alexBrush.variable} ${montserrat.variable} overflow-x-hidden relative`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
  {
    /* </NavcontextProvider> */
  }
}
